### ISSUE TITLE
[spec] Names of fenced frame config mapping members aren't being rendered

### ISSUE THREAD

**Issue by pythagoraskitty** [WICG/fenced-frame#188] opened 2024-09-09 21:22 UTC
For the following definition in the spec:

```
A <dfn>fenced frame config mapping</dfn> has three submappings:

<dl dfn-for="fenced frame config mapping">
  : <dfn>pending config mapping</dfn>
  :: a [=map=] whose [=map/keys=] are [=urn uuids=] and whose [=map/values=] are [=fenced frame
     configs=]

  : <dfn>finalized config mapping</dfn>
  :: a [=map=] whose [=map/keys=] are [=urn uuids=] and whose [=map/values=] are [=fenced frame
     configs=]

  : <dfn>nested config mapping</dfn>
  :: a [=map=] whose [=map/keys=] are [=urn uuids=] and whose [=map/values=] are [=fenced frame
     configs=]
</dl>
```

Here are screenshots in both dark and light modes:
![Screenshot 2024-09-09 at 5 20 07 PM](https://github.com/user-attachments/assets/1ed1b6d4-b539-4fe0-ab89-9970627a9405)
![Screenshot 2024-09-09 at 5 20 47 PM](https://github.com/user-attachments/assets/f0b165aa-6871-47f6-8f9a-6afc3d952533)

**Comment by pythagoraskitty** [comment] 2024-09-09 21:27
Ditto for the similarly defined structs in the spec.  Perhaps this is an issue with my browser, or perhaps this is an issue with this particular spec draft, I'm not sure...

**Comment by pythagoraskitty** [comment] 2024-09-09 21:33
Ran bikeshed myself on this spec on a Linux machine and viewed the resulting HTML there, and it also and the same problem. So this appears to be a real issue.  (My initial report was based on seeing it on my Mac.)

**Comment by domfarolino** [comment] 2024-09-18 02:49
I cannot reproduce this at all, in Chrome Stable or Canary, in a custom build or live on the website, or in Firefox nightly so I really think this is not a generalized issue. Are you still seeing this?

**Comment by domfarolino** [comment] 2024-09-23 18:46
Neither myself nor @shivanigithub can reproduce this sadly, so I think we've got no choice but to close it. Hope the problem is fixed now.

**Closed by domfarolino** 2024-09-23 18:46 UTC
